- pattern: "(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})"
  message: "Slack Token"
  severity: "high"
  id: "slack_token"

- pattern: " PRIVATE KEY-----"
  message: "Generic Private Key POST Encapsulation Boundary"
  severity: "high"
  id: "generic_private_key_post_encapsulation_boundary"

- pattern: " PRIVATE KEY BLOCK-----"
  message: "Generic Private Key Block POST Encapsulation Boundary"
  severity: "high"
  id: "generic_private_key_block_post_encapsulation_boundary"

- pattern: "-----BEGIN PRIVATE KEY-----"
  message: "Private key"
  severity: "high"
  id: "private_key"

- pattern: "-----BEGIN RSA PRIVATE KEY-----"
  message: "RSA private key"
  severity: "high"
  id: "rsa_private_key"

- pattern: "-----BEGIN DSA PRIVATE KEY-----"
  message: "SSH (DSA) private key"
  severity: "high"
  id: "ssh_dsa_private_key"

- pattern: "-----BEGIN EC PRIVATE KEY-----"
  message: "SSH (EC) private key"
  severity: "high"
  id: "ssh_ec_private_key"

- pattern: "-----BEGIN PGP PRIVATE KEY BLOCK-----"
  message: "PGP private key block"
  severity: "high"
  id: "pgp_private_key_block"

- pattern: "AKIA[0-9A-Z]{16}"
  message: "Amazon AWS Access Key ID"
  severity: "high"
  id: "amazon_aws_access_key_id"

- pattern: "amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
  message: "Amazon MWS Auth Token"
  severity: "high"
  id: "amazon_mws_auth_token"

- pattern: "AKIA[0-9A-Z]{16}"
  message: "AWS API Key"
  severity: "high"
  id: "aws_api_key"

- pattern: "R_[0-9a-f]{32}"
  message: "Bitly Key"
  severity: "high"
  id: "bitly_key"

- pattern: "EAACEdEose0cBA[0-9A-Za-z]+"
  message: "Facebook Access Token"
  severity: "high"
  id: "facebook_access_token"

- pattern: "[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*['|\"][0-9a-f]{32}['|\"]"
  message: "Facebook OAuth"
  severity: "high"
  id: "facebook_oauth"

- pattern: "[g|G][i|I][t|T][h|H][u|U][b|B].*['|\"][0-9a-zA-Z]{35,40}['|\"]"
  message: "GitHub"
  severity: "high"
  id: "github"

- pattern: "[a|A][p|P][i|I][_]?[k|K][e|E][y|Y].*['|\"][0-9a-zA-Z]{32,45}['|\"]"
  message: "Generic API Key"
  severity: "high"
  id: "generic_api_key"

- pattern: "[s|S][e|E][c|C][r|R][e|E][t|T].*['|\"][0-9a-zA-Z]{32,45}['|\"]"
  message: "Generic Secret"
  severity: "high"
  id: "generic_secret"

- pattern: "AIza[0-9A-Za-z\\-_]{35}"
  message: "Google API Key"
  severity: "high"
  id: "google_api_key"

- pattern: "AIza[0-9A-Za-z\\-_]{35}"
  message: "Google Cloud Platform API Key"
  severity: "high"
  id: "google_cloud_platform_api_key"

- pattern: "[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com"
  message: "Google Cloud Platform OAuth"
  severity: "high"
  id: "google_cloud_platform_oauth"

- pattern: "AIza[0-9A-Za-z\\-_]{35}"
  message: "Google Drive API Key"
  severity: "high"
  id: "google_drive_api_key"

- pattern: "[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com"
  message: "Google Drive OAuth"
  severity: "high"
  id: "google_drive_oauth"

- pattern: "\"type\": \"service_account\""
  message: "Google (GCP) Service-account"
  severity: "high"
  id: "google_gcp_service_account"

- pattern: "AIza[0-9A-Za-z\\-_]{35}"
  message: "Google Gmail API Key"
  severity: "high"
  id: "google_gmail_api_key"

- pattern: "[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com"
  message: "Google Gmail OAuth"
  severity: "high"
  id: "google_gmail_oauth"

- pattern: "ya29\\.[0-9A-Za-z\\-_]+"
  message: "Google OAuth Access Token"
  severity: "high"
  id: "google_oauth_access_token"

- pattern: "AIza[0-9A-Za-z\\-_]{35}"
  message: "Google YouTube API Key"
  severity: "high"
  id: "google_youtube_api_key"

- pattern: "[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com"
  message: "Google YouTube OAuth"
  severity: "high"
  id: "google_youtube_oauth"

- pattern: "[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}"
  message: "Heroku API Key"
  severity: "high"
  id: "heroku_api_key"

- pattern: "[l|L][i|I][n|N][k|K][e|E][d|D][i|I][n|N].*['|\"][0-9a-zA-Z]{16}['|\"]"
  message: "LinkedIn API Key"
  severity: "high"
  id: "linkedin_api_key"

- pattern: "[0-9a-f]{32}-us[0-9]{1,2}"
  message: "MailChimp API Key"
  severity: "high"
  id: "mailchimp_api_key"

- pattern: "key-[0-9a-zA-Z]{32}"
  message: "Mailgun API Key"
  severity: "high"
  id: "mailgun_api_key"

- pattern: "[a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}[\"'\\s]"
  message: "Password in URL"
  severity: "low"
  id: "password_in_url"

- pattern: "access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}"
  message: "PayPal Braintree Access Token"
  severity: "high"
  id: "paypal_braintree_access_token"

- pattern: "sk_live_[0-9a-z]{32}"
  message: "Picatic API Key"
  severity: "high"
  id: "picatic_api_key"

- pattern: "https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"
  message: "Slack Webhook"
  severity: "high"
  id: "slack_webhook"

- pattern: "sk_live_[0-9a-zA-Z]{24}"
  message: "Stripe API Key"
  severity: "high"
  id: "stripe_api_key"

- pattern: "rk_live_[0-9a-zA-Z]{24}"
  message: "Stripe Restricted API Key"
  severity: "high"
  id: "stripe_restricted_api_key"

- pattern: "sq0atp-[0-9A-Za-z\\-_]{22}"
  message: "Square Access Token"
  severity: "high"
  id: "square_access_token"

- pattern: "sq0csp-[0-9A-Za-z\\-_]{43}"
  message: "Square OAuth Secret"
  severity: "high"
  id: "square_oauth_secret"

- pattern: "SK[0-9a-fA-F]{32}"
  message: "Twilio API Key"
  severity: "high"
  id: "twilio_api_key"

- pattern: "[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*[1-9][0-9]+-[0-9a-zA-Z]{40}"
  message: "Twitter Access Token"
  severity: "high"
  id: "twitter_access_token"

- pattern: "[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*['|\"][0-9a-zA-Z]{35,44}['|\"]"
  message: "Twitter OAuth"
  severity: "high"
  id: "twitter_oauth"

- pattern: " [A-Za-z0-9_]{255}"
  message: "Github OAuth"
  severity: "high"
  id: "github_oauth"

- pattern: "ghp_[a-zA-Z0-9]{30,50}"
  message: "Github PAT Token"
  severity: "high"
  id: "github_pat_token"